Meta tags and basic SEO
kossiitkgp/KWoC-21-Frontend pull request #145
Opened 2023-10-25 19:36 UTC by Alph3ga

2023-10-26 14:13 UTC, harshkhandeparkar requested changes

2023-10-26 14:13 UTC, harshkhandeparkar commented on index.html
> +    <meta property="og:description" content="Oppurtunity for students to explore the world of Free and Open Source Software.">
```suggestion
    <meta property="og:description" content="Opportunity for students to explore the world of Free and Open Source Software.">
```

2023-10-29 08:16 UTC, rajivharlalka commented
LGTM, can merge this! @Alph3ga

2023-10-29 08:17 UTC, rajivharlalka submitted a review, later dismissed

2023-10-29 08:17 UTC, rajivharlalka commented
@harshkhandeparkar approve krde?

2023-10-29 14:16 UTC, harshkhandeparkar commented
> @harshkhandeparkar approve krde?

There is one issue that still needs to be resolved. Check Slack.

2023-10-30 15:36 UTC, harshkhandeparkar approved these changes
Wasted enough time to make it work on Whatsapp. No more time needs to be wasted.

2023-10-30 15:36 UTC, merged