Navbar
kossiitkgp/KWoC-21-Frontend pull request #152
Opened 2023-10-27 17:24 UTC by Nafisay

2023-10-27 19:01 UTC, harshkhandeparkar requested changes

2023-10-27 19:01 UTC, harshkhandeparkar commented on src/App.tsx
> +import Navbar from './components/Navbar'
```suggestion
import Navbar from './components/Navbar';
```

for consistency

2023-10-27 19:01 UTC, harshkhandeparkar commented on src/App.tsx
> +    <div className="App">
```suggestion
    <div className="App">
```

2023-10-27 19:01 UTC, harshkhandeparkar commented on src/App.tsx
> +      <Navbar />
Indent this and everything inside `BrowserRouter`

2023-10-27 19:01 UTC, harshkhandeparkar commented on src/assets/image.png
Please remove this file since it is not used

2023-10-29 08:20 UTC, rajivharlalka commented
Update? @Nafisay

2023-10-29 14:17 UTC, harshkhandeparkar requested changes

2023-10-29 14:17 UTC, harshkhandeparkar commented on src/assets/login.svg
Please use existing icon libraries instead of using custom icons.

2023-11-03 21:37 UTC, harshkhandeparkar approved these changes

2023-11-03 21:37 UTC, merged