mouse transition effect
kossiitkgp/KWoC-21-Frontend pull request #217
Opened 2023-12-10 09:44 UTC by MitulSonagara

# Title and Issue number 
Title : Mouse Transition Effect

Issue No. : #214 

Close #214

**Additional context (Mandatory )**
I have created the mouse transition effect as per demo given in my issue detail... please review this and give me further improvements.

2023-12-10 15:09 UTC, Nafisay commented
@MitulSonagara as you can see that the snowflakes have a dark border which does not match the snowflakes of the landing page. Please make the required changes so as they match the theme

2023-12-10 15:10 UTC, Nafisay commented
Also can you make the number of snowflakes more sparse and slower. I think it will look good that way

2023-12-10 15:14 UTC, MitulSonagara commented
Sure, I can try that way also...

2023-12-10 15:15 UTC, MitulSonagara commented
Can you please provide me that the snow flakes are images or any emoji...

2023-12-10 15:23 UTC, Nafisay commented
You will find the snowflakes svg file here
[https://github.com/kossiitkgp/KWoC-Frontend/tree/truth-redefined-again/src/assets](url)

Note that there are 3 types of snowflakes involved. Try to incorporate all of them

2023-12-11 10:16 UTC, MitulSonagara commented
@Nafisay I have updated the code. But i can not see the changes on the deployment but i can see this on my local server... can you please check it.

2023-12-11 12:15 UTC, Nafisay commented
Same, even I can't see them

2023-12-11 13:30 UTC, MitulSonagara commented
I'll inform you after some changes...

2023-12-18 05:46 UTC, Nafisay commented
Sorry I can't see any changes

2023-12-30 10:59 UTC, harshkhandeparkar commented
@MitulSonagara were you able to debug the issue?

2023-12-30 11:00 UTC, harshkhandeparkar requested changes

2023-12-30 11:00 UTC, harshkhandeparkar commented on index.html
> +  <script>
Please do not add javascript directly. Use react.

2023-12-30 11:01 UTC, harshkhandeparkar commented
If you are unable to debug this, I would suggest closing this PR since it is not very important. Also adding transition effects linked to the mouse might lead to performance issues (we had removed some effects due to this earlier).

2023-12-30 11:38 UTC, closed without merging