Enhanced search box
kossiitkgp/KWoC-21-Frontend pull request #218
Opened 2023-12-11 06:27 UTC by Jaimin25

# Improved search box in projects and FAQ page
The clear button will not be visible when query is empty and added a clear button on FAQ page

close #215 

https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/3cf128b3-abf1-45ab-bcdd-0acf64d6287a

2023-12-11 07:00 UTC, Nafisay requested changes

2023-12-11 07:00 UTC, Nafisay commented on src/pages/FAQ.tsx
> +        <div className="flex py-4 px-6 rounded-md outline-none w-[80vw] max-w-3xl border-none text-white bg-slate-900 font-semibold bg-none">
can you indent this properly (just to look professional)

2023-12-11 07:00 UTC, Nafisay commented on src/pages/Projects.tsx
> +          }
put this brace in the above line (to maintain uniformity with the other codes)

2023-12-11 07:00 UTC, Nafisay commented on src/pages/FAQ.tsx
> -
please keep this extra line, the code looks clean this way

2023-12-11 11:06 UTC, Nafisay commented
Good work!

2023-12-11 11:57 UTC, Nafisay approved these changes

2023-12-11 13:46 UTC, harshkhandeparkar approved these changes

2023-12-12 18:37 UTC, merged

2023-12-12 18:37 UTC, harshkhandeparkar commented
Thanks @Jaimin25! :rocket: