#213 issue: update mentor dashboard stats
kossiitkgp/KWoC-21-Frontend pull request #226
Opened 2023-12-23 06:59 UTC by pranjal3060

Added Total Commits and Total Pull Requests : Calculated and displayed the total number of commits and pull requests across all projects.

Added Total Projects and Approved Projects : Included the count of total projects and approved projects in the overall statistics section.

2023-12-23 09:29 UTC, harshkhandeparkar requested changes

2023-12-23 09:29 UTC, harshkhandeparkar commented on README.md
> +## Changes Overview
You don't need to add anything here :)

2023-12-23 09:29 UTC, harshkhandeparkar commented on src/data/FAQs.ts
> -      "Commits are counted only after your PR is merged in the mentor's repository. The PR must be opened using the Github account you logged in with and your username should not be changed during th
Is this a mistake?

2023-12-23 09:31 UTC, harshkhandeparkar commented
@pranjal3060 Can you send a screenshot of the full mentor dashboard with the changes? Thanks.

2023-12-23 09:32 UTC, harshkhandeparkar commented
@pranjal3060 also run `pnpm build` locally and fix any errors that are shown.

2023-12-23 09:53 UTC, pranjal3060 commented
> @pranjal3060 Can you send a screenshot of the full mentor dashboard with the changes? Thanks.

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/119282619/d2cf2b84-6a02-4c1c-acec-a0dacc14c89b)

2023-12-23 09:55 UTC, pranjal3060 commented
> @pranjal3060 Can you send a screenshot of the full mentor dashboard with the changes? Thanks.

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/119282619/1a398f87-9d53-482d-a686-089a3faf19b7)

2023-12-23 12:21 UTC, harshkhandeparkar requested changes
The build is still failing. Please run `pnpm build` and fix the issues.

2023-12-23 12:21 UTC, harshkhandeparkar commented on src/pages/MentorDashboard.tsx
> +      project.commits.forEach((commit) => {
Shouldn't this be `project.pulls`?

2023-12-23 12:21 UTC, harshkhandeparkar commented on src/pages/MentorDashboard.tsx
> +                <p className="font-bold text-base">{approvedProjects}</p>
Can we display `{approvedProjects} / {totalProjects}` here?

2023-12-23 12:21 UTC, harshkhandeparkar commented
> > @pranjal3060 Can you send a screenshot of the full mentor dashboard with the changes? Thanks.
> 
> ![image](https://private-user-images.githubusercontent.com/119282619/292620071-1a398f87-9d53-482d-a686-089a3faf19b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzQzNjYsIm5iZiI6MTcwMzMzNDA2NiwicGF0aCI6Ii8xMTkyODI2MTkvMjkyNjIwMDcxLTFhMzk4Zjg3LTlkNTMtNDgyZC1hNjg2LTA4OWEzZmFmMTliNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxMjIxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2Q1MzBhNTdjMjhlNTM4NzJhZjdlODEyNjE1Nzc5MzA4YmY3YmY2ZmQ4NDI4M2Q2MWVmZDVhNDJlNzkzMDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nk60v7J_FfwKdG1jO4VuwJdZ1lpoLeo1Ddgp3Q3GRYk)

Can you send one with some pull requests displayed?

2023-12-25 10:42 UTC, harshkhandeparkar commented on src/pages/MentorDashboard.tsx
> +      project.commits.forEach((commit) => {
nvm

2023-12-25 10:42 UTC, harshkhandeparkar commented on src/pages/MentorDashboard.tsx
> +                <p className="font-bold text-base">{approvedProjects}</p>
it's already displayed sorry

2023-12-25 10:43 UTC, merged

2023-12-25 10:43 UTC, harshkhandeparkar commented
Thanks @pranjal3060!