Blog Form
kossiitkgp/KWoC-21-Frontend pull request #235
Opened 2024-01-11 15:24 UTC by Nafisay

2024-01-11 16:26 UTC, harshkhandeparkar requested changes

2024-01-11 16:26 UTC, harshkhandeparkar commented on src/App.tsx
> +            <BlogForm />
Add it to the router.

2024-01-11 16:26 UTC, harshkhandeparkar commented on src/pages/BlogForm.tsx
> +      placeholder: "",
Add any placeholder, like a medium link.

2024-01-11 16:26 UTC, harshkhandeparkar commented on src/pages/BlogForm.tsx
> +
Add a condition here to redirect to home page if the user is not logged in.

2024-01-12 09:39 UTC, Nafisay commented on src/App.tsx
> +            <BlogForm />
i put `STUDENT_DASHBOARD` as path

2024-01-13 10:34 UTC, merged